name: Deploy to Vercel

# mainブランチにpushをトリガーにする
on:
  push:
    branches:
      - main 

# ジョブを定義
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # リポジトリのコードをクローンする

      - uses: actions/setup-node@v4 # node.jsをセットアップする
        with:
          node-version: '22'        # nodeのバージョン22を指定
      - name: Install dependencies
        run: npm install
      - name: Check environment variables # 環境変数が設定されているか確認
        run: |
          if [ -z "${{ secrets.VITE_SUPABASE_URL }}" ]; then echo "VITE_SUPABASE_URL is not set"; else echo "VITE_SUPABASE_URL is set"; fi
          if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then echo "VITE_SUPABASE_ANON_KEY is not set"; else echo "VITE_SUPABASE_ANON_KEY is set"; fi
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then echo "VERCEL_ORG_ID is not set"; else echo "VERCEL_ORG_ID is set"; fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then echo "VERCEL_PROJECT_ID is not set"; else echo "VERCEL_PROJECT_ID is set"; fi
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then echo "VERCEL          
      - name: Run test (CI)
        run: npm test
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Debug env
        run: |
          echo "URL=$VITE_SUPABASE_URL"
          echo "KEY=$VITE_SUPABASE_ANON_KEY"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Run build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
